mukadi_wallet:
    classes:
        authorization: App\Entity\Authorization
        channel: App\Entity\Channel
        counter: App\Entity\Counter
        holder: App\Entity\Holder
        holder_profil: App\Entity\HolderProfil
        instruction: App\Entity\Instruction
        operation: App\Entity\Operation
        platform: App\Entity\Platform
        request_type: App\Entity\RequestType
        schema: App\Entity\Schema
        transaction: App\Entity\Transaction
        transaction_history: App\Entity\TransactionHistory
        wallet: App\Entity\Wallet
        wallet_type: App\Entity\WalletType    