os: linux
env:
    - SKELETON_VERSION="^5.0"
php: 7.4
dist: trusty
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
before_install:
    - composer self-update
script:
    - composer require mukadi/wallet-bundle 2.0.0
install:
    - composer create-project symfony/skeleton:${SKELETON_VERSION} app
    - cd app
    - composer config extra.symfony.allow-contrib false
language: php