Mukadi\WalletBundle\Model\Counter:
    type: mappedSuperclass
    fields:
        ref:
            type: string
            length: 2
            unique: true
            column: counter_ref
        counter:
            type: smallint
            column: counter_counter