Mukadi\WalletBundle\Model\HolderProfil:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    indexes:
        idx_hp_pif:
            columns: [hp_pif]
    fields:
        code:
            type: string
            length: 4
            unique: true
            column: hp_code
        platformId:
            type: string
            length: 16
            column: hp_pif
        label:
            type: string
            length: 20
            column: hp_label