Mukadi\WalletBundle\Model\Instruction:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    indexes:
        idx_ins_sch_id:
            columns: [ins_sch_id]
        idx_ins_order:
            columns: [ins_order]
    fields:
        amount:
            type: string
            length: 255
            column: ins_amt
        currency:
            type: string
            length: 255
            column: ins_currency
        direction:
            type: string
            length: 255
            column: ins_dir
        label:
            type: string
            length: 255
            column: ins_label
        order:
            type: smallint
            column: ins_order
        wallet:
            type: string
            length: 255
            column: ins_wallet
        schemaId:
            type: string
            length: 16
            column: ins_sch_id