Mukadi\WalletBundle\Model\Platform:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        platformId:
            type: string
            length: 16
            unique: true
            column: platform_id                
        label:
            type: string
            length: 20
            column: platform_label