Mukadi\WalletBundle\Model\Platform:
    type: mappedSuperclass
    fields:
        platformId:
            type: string
            length: 16
            unique: true
            column: platform_id                
        label:
            type: string
            length: 20
            column: platform_label