Mukadi\WalletBundle\Model\Schema:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    indexes:
        idx_sch_pif:
            columns: [sch_pif]
        idx_sch_code:
            columns: [sch_code]
    fields:
        code:
            type: string
            length: 4
            column: sch_code
        platformId:
            type: string
            length: 16
            column: sch_pif
        schemaId:
            type: string
            length: 16
            unique: true
            column: sch_id