Mukadi\WalletBundle\Model\WalletType:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    indexes:
        idx_wtp_pif:
            columns: [wtp_pif]
    fields:
        code:
            type: string
            length: 4
            unique: true
            column: wtp_code
        label:
            type: string
            length: 20
            column: wtp_label
        platformId:
            type: string
            length: 16
            column: wtp_pif