services:
    mukadi_wallet.strategy.default_id_generator:
        public: true
        class: Mukadi\WalletBundle\Strategy\DefaultIdGeneratorStrategy
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%mukadi_wallet_counter_class%'
    mukadi_wallet.strategy.default_wallet_naming:
        public: true
        class: Mukadi\WalletBundle\Strategy\DefaultWalletNamingStrategy
        arguments:
            - '@mukadi_wallet.strategy.id_generator'
    Mukadi\WalletBundle\Model\Strategy\IdGeneratorStrategy:
        alias: mukadi_wallet.strategy.id_generator
    Mukadi\WalletBundle\Model\Strategy\WalletNamingStrategy:
        alias: mukadi_wallet.strategy.wallet_naming                    